/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface PostDetails {
    /**
    * The content data
    */
    'contentData': any;
    /**
    * The content url
    */
    'contentUrl': string;
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface PostDetailsAttributes extends StencilHTMLAttributes {
    /**
    * The content data
    */
    'contentData'?: any;
    /**
    * The content url
    */
    'contentUrl'?: string;
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface PostList {
    /**
    * The content data
    */
    'contentData': any;
    /**
    * The content url
    */
    'contentUrl': string;
    'history': RouterHistory;
  }
  interface PostListAttributes extends StencilHTMLAttributes {
    /**
    * The content data
    */
    'contentData'?: any;
    /**
    * The content url
    */
    'contentUrl'?: string;
    'history'?: RouterHistory;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PostDetails': Components.PostDetails;
    'PostList': Components.PostList;
  }

  interface StencilIntrinsicElements {
    'post-details': Components.PostDetailsAttributes;
    'post-list': Components.PostListAttributes;
  }


  interface HTMLPostDetailsElement extends Components.PostDetails, HTMLStencilElement {}
  var HTMLPostDetailsElement: {
    prototype: HTMLPostDetailsElement;
    new (): HTMLPostDetailsElement;
  };

  interface HTMLPostListElement extends Components.PostList, HTMLStencilElement {}
  var HTMLPostListElement: {
    prototype: HTMLPostListElement;
    new (): HTMLPostListElement;
  };

  interface HTMLElementTagNameMap {
    'post-details': HTMLPostDetailsElement
    'post-list': HTMLPostListElement
  }

  interface ElementTagNameMap {
    'post-details': HTMLPostDetailsElement;
    'post-list': HTMLPostListElement;
  }


}
